version: '3.8'

services:
  web:
    image: python:3.10-slim
    container_name: django_app
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - C:/Users/Quirence/PycharmProjects/PythonScrap:/app  # Локальная папка -> контейнер
    working_dir: /app  # В контейнере ваш проект будет находиться в директории /app
    ports:
      - "8000:8000"  # Открываем порт для доступа
    environment:
      - PYTHONUNBUFFERED=1  # Отключение буферизации для логов
